### ISSUE TITLE
LHIK flickers when using physbullets and scopes

### ISSUE THREAD

**Issue by DraganTMCE** [HaodongMo/ArcCW#135] opened 2022-11-03 06:19 UTC
This issue is still happening even ws & github branch. When you try to put only a sights & underbarrel attachments but without muzzle
attachments, the vm hands flickering itself. But if you put muzzle attachments on, with sights & underbarrel attachments, it stop flickering somehow.

**Comment by SpiffyJUNIOR** [comment] 2022-11-11 02:09
can verify, 8z pls fix

**Comment by TheOnly8Z** [comment] 2022-12-20 05:24
Can replicate but only with physbullets turned on.

**Comment by Jayrazer** [comment] 2022-12-20 15:34
Verified this is actually still happening, but now occurs only on RT scopes if not using cheap scopes.

https://user-images.githubusercontent.com/79886161/208704818-4235e014-e920-438c-b407-89e370f538ae.mp4

**Comment by Fesiug** [comment] 2022-12-20 21:59
I don't use Cheap Scopes, but this doesn't happen to me. @TheOnly8Z can you see if this happens to you

**Comment by SpiffyJUNIOR** [comment] 2022-12-20 22:02
chiming in to say that i can't reproduce either

**Comment by Fesiug** [comment] 2022-12-20 22:09
@Jayrazer Check and make sure you are up to date on the git version of ArcCW, and then see if you may have conflicting addons.

**Comment by Jayrazer** [comment] 2022-12-20 22:50
Re-cloned Github build of the base, factory reset GMod and disabled all addons and it still occurs.

https://user-images.githubusercontent.com/79886161/208781377-9bf38dd2-143e-4b23-ad1a-528810eda191.mp4

**Comment by littlebabyman** [comment] 2022-12-21 02:35
Can replicate. x64 branch.
https://user-images.githubusercontent.com/3816236/208806913-fef3acf9-e315-40c3-894c-3b1e71f71339.mp4

**Comment by Fesiug** [comment] 2022-12-21 03:25
Can replicate. Physical Bullets on, have a underbarrel foregrip, RT optic, cheap scopes OFF

**Comment by TheOnly8Z** [comment] 2022-12-21 20:02
> Can replicate. Physical Bullets on, have a underbarrel foregrip, RT optic, cheap scopes OFF, singleplayer, x64

Okay, It appears that turning on "Draw barrel in RT scopes" will prevent the issue from occuring. Somehow.

**Comment by TheOnly8Z** [comment] 2022-12-21 20:22
Hopefully fixed for real. @Fesiug @littlebabyman @Jayrazer Please confirm and we can close this issue.

**Comment by Jayrazer** [comment] 2022-12-21 21:41
Confirmed fixed.  Phys bullets on, underbarrel, RT optic, cheap scopes off, draw barrel in RT off, singleplayer x64 branch and no issues.  We can close this now.

**Closed** 2022-12-23 06:27 UTC
