### ISSUE TITLE
Sprinting Animation Bug

### ISSUE THREAD

**Issue by thejaviertc** [HaodongMo/ArcCW#65] opened 2021-05-08 16:40 UTC
If you sprint and switch to other weapon while sprinting, when you take again the weapon which you were sprinting, the weapon starts bugging: https://user-images.githubusercontent.com/45662206/117546783-7b61f900-b02c-11eb-8c50-e017a80cbff9.mp4

You can reload and the bug will remain there until you aim: https://user-images.githubusercontent.com/45662206/117546820-b401d280-b02c-11eb-9c32-78359d03a74e.mp4

**Comment by TheOnly8Z** [comment] 2021-06-10 10:30
Duplicate of #62. Will verify and investigate soon

**Closed by TheOnly8Z** 2021-06-10 10:30 UTC
