### ISSUE TITLE
Crashes when shooting Photon Cars

### ISSUE THREAD

**Issue by thejaviertc** [HaodongMo/ArcCW#58] opened 2021-04-19 19:53 UTC
Hello,
I'm a developer from a DarkRP server, an I'm having an issue with the ArcCW Weapons + Gunsmith Offensive.

Sometimes when the users are in a shooting with the police, when they shoot a police car (Only happens with vehicles that have Photon lights) the users that are near sometimes crashes, and this error spams the console:

```
[[ArcCW] Arctic's Customizable Weapons (Base Only)] lua/effects/arccw_tracer.lua:26: attempt to call method 'GetBuff_Override' (a nil value)
  1. unknown - lua/effects/arccw_tracer.lua:26
```
(Also we use VCMod)

What could I do? Is an error of the addon?
Regards

**Comment by datae-git** [comment] 2021-04-20 06:30
Can you try to reproduce the issue consistently in a controlled environment (e.g local server with just arccw and photon) and see if it still crashes?

**Comment by TheOnly8Z** [comment] 2021-04-20 07:15
Please ensure r_drawmodeldecals is 0, it is known to crash when generating decals on high poly models like cars.

**Comment by thejaviertc** [comment] 2021-04-20 15:33
#

> Can you try to reproduce the issue consistently in a controlled environment (e.g local server with just arccw and photon) and see if it still crashes?

I will try to do it, because is a litte bit strange. Only happends when there are some people shooting. The users said that sometimes when they shoot the police car, people nearby the car crashes (sometimes I have seen like 5 people disconnected with timed out at the same time). 
I tried shooting the car alone and nothing happens, but with some people around and shooting, the error start spamming and some people crashes. I will try to record it.



> Please ensure r_drawmodeldecals is 0, it is known to crash when generating decals on high poly models like cars.

I will test it and see if it works.

**Comment by TheOnly8Z** [comment] 2021-05-05 15:12
Closing as I assume the issue is related to r_drawmodeldecals. Let us know if that is not the case.

**Closed by TheOnly8Z** 2021-05-05 15:12 UTC

**Comment by thejaviertc** [comment] 2021-05-05 16:48
Sorry, I completely forgot.
Problem is solved.

Thanks you very much
